apiVersion: v1
kind: Service
metadata:
  name: gke-circleci-service
spec:
  selector:
    app: gke-circleci
  type: LoadBalancer
  ports:
    - name: gke-circleci-port
      port: 8080
      targetPort: 8080