apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-circleci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-circleci
  template:
    metadata:
      labels:
        app: gke-circleci
    spec:
      containers:
        - image: gcr.io/stupidgke/gke-circleci:v1.0
          name: gke-circleci
          imagePullPolicy: Always
          tty: true