apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-circleci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-circleci
  template:
    metadata:
      labels:
        app: gke-circleci
    spec:
      containers:
        - image: node:10-alpine
          name: gke-circleci
          tty: true