apiVersion: v1
kind: Service
metadata:
  name: gke-circleci-service
spec:
  selector:
    app: gke-circleci
  type: NodePort
  ports:
    - name: gke-circleci-port
      port: 3000
      targetPort: 8080