version: 2.0
jobs:
  build_and_test:
    working_directory: ~/server
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: ~/server
          paths:
            - src/*
          
  deploy_to_staging:
    attach_workspace:
      - at: src/
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTER_ZONE}
      - run:
          name: Connect to cluster
          command: |
            gcloud container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run:
          name: Create deployment
          command: |
            kubectl create --dry-run=true -o yaml -f k8s.deployment.yml | kubectl apply -f -
      - run:
          name: Create service
          command: |
            kubectl create --dry-run=true -o yaml -f k8s.service.yml | kubectl apply -f -
      - run:
          name: Get pods
          command: |
            kubectl get pods
            kubectl describe pods

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy_to_staging:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
